// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { StoragesHealthData, StoragesHealthErrors, StoragesHealthResponses, StoragesProtectedProbeData, StoragesProtectedProbeErrors, StoragesProtectedProbeResponses, StoragesProtectedWriteData, StoragesProtectedWriteErrors, StoragesProtectedWriteResponses, StoragesReadData, StoragesReadErrors, StoragesReadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness probe.
 */
export const storagesHealth = <ThrowOnError extends boolean = false>(options?: Options<StoragesHealthData, ThrowOnError>): RequestResult<StoragesHealthResponses, StoragesHealthErrors, ThrowOnError> => (options?.client ?? client).get<StoragesHealthResponses, StoragesHealthErrors, ThrowOnError>({ url: '/storages/health', ...options });

/**
 * Role-gated probe (clinician, tenant-admin).
 */
export const storagesProtectedProbe = <ThrowOnError extends boolean = false>(options?: Options<StoragesProtectedProbeData, ThrowOnError>): RequestResult<StoragesProtectedProbeResponses, StoragesProtectedProbeErrors, ThrowOnError> => (options?.client ?? client).get<StoragesProtectedProbeResponses, StoragesProtectedProbeErrors, ThrowOnError>({ url: '/storages/protected', ...options });

/**
 * Demonstration write - actor bound to the JWT principal.
 */
export const storagesProtectedWrite = <ThrowOnError extends boolean = false>(options: Options<StoragesProtectedWriteData, ThrowOnError>): RequestResult<StoragesProtectedWriteResponses, StoragesProtectedWriteErrors, ThrowOnError> => (options.client ?? client).post<StoragesProtectedWriteResponses, StoragesProtectedWriteErrors, ThrowOnError>({
    url: '/storages/protected-write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Diamond-root scoped read by id.
 */
export const storagesRead = <ThrowOnError extends boolean = false>(options: Options<StoragesReadData, ThrowOnError>): RequestResult<StoragesReadResponses, StoragesReadErrors, ThrowOnError> => (options.client ?? client).get<StoragesReadResponses, StoragesReadErrors, ThrowOnError>({ url: '/storages/{id}', ...options });
