// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type DeleteAck = {
    id: string;
    deleted: boolean;
};

/**
 * Liveness probe result - any authenticated principal may call it.
 */
export type HealthStatus = {
    status: string;
    layer: string;
};

export type ProblemResponse = {
    statusCode?: number;
    status?: number;
    error?: string;
    message: string | Array<string>;
};

/**
 * Scoped single-resource read result.
 */
export type StorageRead = {
    id: string;
    status: string;
    layer: string;
    actorId: string;
};

export type StorageWriteInput = {
    /**
     * Optional free-text reason captured on the write. Trimmed runtime-side by Zod.
     */
    reason?: string;
};

export type WormLockProblem = {
    statusCode: 403;
    error: 'worm_lock';
    retention_until: string;
    message: string;
};

/**
 * Result of the demonstration write - actorId is the JWT-derived principal, never body-supplied.
 */
export type WriteAck = {
    status: string;
    layer: string;
    actorId: string;
};

export type ObjectsDeleteData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/objects/{id}';
};

export type ObjectsDeleteErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: WormLockProblem;
    /**
     * The server cannot find the requested resource.
     */
    404: ProblemResponse;
};

export type ObjectsDeleteError = ObjectsDeleteErrors[keyof ObjectsDeleteErrors];

export type ObjectsDeleteResponses = {
    /**
     * The request has succeeded.
     */
    200: DeleteAck;
};

export type ObjectsDeleteResponse = ObjectsDeleteResponses[keyof ObjectsDeleteResponses];

export type StoragesHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/storages/health';
};

export type StoragesHealthErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
};

export type StoragesHealthError = StoragesHealthErrors[keyof StoragesHealthErrors];

export type StoragesHealthResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type StoragesHealthResponse = StoragesHealthResponses[keyof StoragesHealthResponses];

export type StoragesProtectedProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/storages/protected';
};

export type StoragesProtectedProbeErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type StoragesProtectedProbeError = StoragesProtectedProbeErrors[keyof StoragesProtectedProbeErrors];

export type StoragesProtectedProbeResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type StoragesProtectedProbeResponse = StoragesProtectedProbeResponses[keyof StoragesProtectedProbeResponses];

export type StoragesProtectedWriteData = {
    body: StorageWriteInput;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/storages/protected-write';
};

export type StoragesProtectedWriteErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ProblemResponse;
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type StoragesProtectedWriteError = StoragesProtectedWriteErrors[keyof StoragesProtectedWriteErrors];

export type StoragesProtectedWriteResponses = {
    /**
     * The request has succeeded.
     */
    200: WriteAck;
};

export type StoragesProtectedWriteResponse = StoragesProtectedWriteResponses[keyof StoragesProtectedWriteResponses];

export type StoragesReadData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/storages/{id}';
};

export type StoragesReadErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ProblemResponse;
};

export type StoragesReadError = StoragesReadErrors[keyof StoragesReadErrors];

export type StoragesReadResponses = {
    /**
     * The request has succeeded.
     */
    200: StorageRead;
};

export type StoragesReadResponse = StoragesReadResponses[keyof StoragesReadResponses];
